from bs4 import BeautifulSoup
#from bing import Bing
from google import Google
import unittest

GOOGLE_NEWS_RESULT = [
    {'link': 'http://www.directlyrics.com/kid-ink-hello-world-music-video-news.html&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CBMQqQIoADAB&usg=AFQjCNHZCZBM9HbRDjZPMcDwSpHL08oaXA', 'link_text': "Kid Ink - ' Hello World ' [Music Video]", 'additional_links': {'Kid Ink \x96 \x93 Hello World \x94 (Video)': ('/url?q=http://allhiphop.com/2015/01/01/kid-ink-hello-world-video/&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CBYQ-AsoATAB&usg=AFQjCNHqprZiqId_X_J-NLyYRHorUYFv0Q', 'AllHipHop'), "Kid Ink Shares Globe-Spanning ' Hello World ' Music Video [WATCH]": ('/url?q=http://www.musictimes.com/articles/22570/20141231/kid-ink-globe-spanning-hello-world-music-video.htm&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CBUQ-AsoADAB&usg=AFQjCNEM1EcBBGYTmnm8SAmClTYZL0x70g', 'Music Times')}, 'link_info': "In his latest visual release ' Hello World ', the Los Angeles rapper recaps his adventures all throughout the year into a three minute clip directed ...", 'time': '1 day ago', 'source': 'Music and Lyrics'},
    {'link': 'http://www.staplesworld.com/news/2015-01-01/Life_Currents/Hello_World.html&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CBkQqQIoADAC&usg=AFQjCNHNGs71QQ9onauWedVdbgULEK_v9Q', 'link_text': 'Hello World', 'additional_links': {}, 'link_info': 'BIRTHS REPORTED AT LAKEWOOD HEALTH SYSTEM HOSPITAL INCLUDED: Born to Bryan and Kripa Reese of Staples, a baby girl, ...', 'time': '2 days ago', 'source': 'Staples World (subscription)'},
    {'link': 'https://medium.com/backchannel/hello-world-cf8dd6fcb7f7&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CBsQqQIoADAD&usg=AFQjCNEXjijyJV3AHgIEagz0wyyOF0TBvQ', 'link_text': 'Hello , World !', 'additional_links': {}, 'link_info': 'You may even be able to work out, more or less, what this little \x93Program\x94 does: it writes to the console of some system the line \x93 Hello , world !\x94 A geek hunched ...', 'time': '19 Dec 2014', 'source': 'Backchannel'},
    {'link': 'http://www.osnews.com/story/28131/The_infamous_Windows_Hello_World_program&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CB4QqQIoADAE&usg=AFQjCNFhKJJwlNS2dTP2soFiX1Gc0iatKw', 'link_text': 'The infamous Windows " Hello World " program', 'additional_links': {}, 'link_info': 'I learned Windows programming from documents included with the Windows 1.0 beta and release Software Development Kits. These included ...', 'time': '9 Dec 2014', 'source': 'OS News'},
    {'link': 'http://www.fool.com.au/2014/12/12/helloworld-ltd-surges-on-positive-new-should-you-bet-on-it-for-2015/&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CCAQqQIoADAF&usg=AFQjCNHu2J_8HgVDvsQTsG5QLaIZSCxX7Q', 'link_text': 'Helloworld Ltd surges on positive new: Should you bet on it for 2015?', 'additional_links': {}, 'link_info': 'Helloworld Ltd (ASX: HLO) shares have skyrocketed today after the company announced that one of its subsidiaries, QBT Limited, had been ...', 'time': '11 Dec 2014', 'source': 'Motley Fool Australia'},
    {'link': 'http://mumbrella.com.au/travel-firm-helloworld-appoints-marketer-jane-mckellar-new-board-member-268338&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CCQQqQIoADAG&usg=AFQjCNE7SvfNPq3rC_j3OSFydFJjYRkLJg', 'link_text': 'Travel firm Helloworld appoints marketer Jane McKellar as new ...', 'additional_links': {}, 'link_info': 'Helloworld Limited (ASX:HLO) is pleased to announce the appointment of Ms Jane McKellar as an independent Non-Executive Director ...', 'time': '16 Dec 2014', 'source': 'MuMbrella'},
    {'link': 'http://www.fool.com.au/2014/12/11/cover-more-group-ltd-and-helloworld-ltd-announce-positive-news-should-you-buy/&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CCgQqQIoADAH&usg=AFQjCNGSA-g_H9sPhTQA6yP_FCFvKVp1Cw', 'link_text': 'Cover-More Group Ltd and Helloworld Ltd announce positive news ...', 'additional_links': {'Cover-More beats competition for Helloworld preferred status': ('/url?q=http://www.travelweekly.com.au/news/cover-more-beats-competition-for-helloworld-prefer&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CCoQ-AsoADAH&usg=AFQjCNHu3l7KaLX-nsVbNn5zq_4HMJXksw', 'Travel Weekly')}, 'link_info': 'Cover-More Group Ltd (ASX: CVO) and Helloworld Ltd (ASX: HLO) have reached an agreement which will see Cover-More become the ...', 'time': '10 Dec 2014', 'source': 'Motley Fool Australia'},
    {'link': 'http://www.nbcnews.com/news/world/hello-2015-new-year-rung-around-world-n277466&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CC0QqQIoADAI&usg=AFQjCNF1_XGw55g3JMJKF4wPPeFxNbMpQw', 'link_text': 'Hello , 2015! A New Year Is Rung In Around the World', 'additional_links': {"New Year's Eve: Watch the world ring in 2015": ('/url?q=http://www.haaretz.com/news/world/1.634707&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CDAQ-AsoATAI&usg=AFQjCNHqeKXiTua-zmUVxl3GZ7I7eE7ugw', 'Haaretz'), 'World rings in New Year': ('/url?q=http://www.reuters.com/video/2014/12/31/world-rings-in-new-year%3FvideoId%3D357271665&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CC8Q-AsoADAI&usg=AFQjCNHAfLrPCH4PQFYLnDgeodfZ8V2MlA', 'Reuters'), 'Hello , 2015! See New Year Celebrations Around the World': ('/url?q=http://www.bayoubuzz.com/top-stories/item/808469-hello-2015-see-new-year-celebrations-around-the-world&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CDEQ-AsoAjAI&usg=AFQjCNEYiPZtAz0xKqrGruII02BXU59z4A', 'Bayoubuzz')}, 'link_info': 'MUNICH, Germany \x97 Neo-Nazis are keeping their black combat boots and bomber jackets in the closet as they try to force their way into mainstream German ...', 'time': '1 day ago', 'source': 'NBCNews.com'},
    {'link': 'http://www.dailymercury.com.au/news/helloworlds-alyce-best-in-australia/2486084/&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CDQQqQIoADAJ&usg=AFQjCNFDbOrVHdyoebQJInpYl2I_Z9djTQ', 'link_text': "Helloworld's Alyce best in Australia", 'additional_links': {}, 'link_info': 'Head of helloworld -branded network Julie Primmer, Team Spirit Award winner Alyce Tweddle and event host Stevie Jacobs from the Today ...', 'time': '15 Dec 2014', 'source': 'Mackay Daily Mercury'},
    {'link': 'http://www.mediapost.com/publications/article/240253/helloworld-mellow-mushroom-stella-artois-launch.html&sa=U&ei=3QGnVKerC9CouQTY1oC4Dg&ved=0CDcQqQIoADAK&usg=AFQjCNFYKt6wpBUqJjymlKdTIj2cOXXTCA', 'link_text': 'HelloWorld , Mellow Mushroom, Stella Artois Launch Holiday ...', 'additional_links': {}, 'link_info': 'Mellow Mushroom, digital agency HelloWorld and beer brand Stella Artois are sponsoring a sweepstakes where customers can follow Mellow ...', 'time': '16 Dec 2014', 'source': 'MediaPost Communications'}
    ]

class BingTest(unittest.TestCase):

    def test_google_scrape_news_result(self):
        with open('ipgooglenews') as fp:
            google_news_result = Google.scrape_news_result(BeautifulSoup(fp))
            self.assertEqual(GOOGLE_NEWS_RESULT, google_news_result)

if __name__ == '__main__':
    unittest.main()

print(Google.search_news('usa', 2, 0, True, 'w', "es"))